export const userData = {
  name: "Founders",
  designation: "Founders",
  email: "",
  manager: "",
  children: [
    {
      name: "Alice Anderson",
      designation: "Founder",
      email: "alice.anderson@example.com",
      manager: "",
      score: "95",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEO0x4WIph6alSzi8J9p55nOxJvw9FdCPR3A&usqp=CAU",
      children: [],
    },
    {
      name: "Bob Barker",
      designation: "Founder",
      email: "bob.barker@example.com",
      manager: "",
      score: "96",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLe5PABjXc17cjIMOibECLM7ppDwMmiDg6Dw&usqp=CAU",
      children: [],
    },
    {
      name: "Carol CEO",
      designation: "CEO",
      email: "carol.ceo@example.com",
      manager: "Alice Anderson",
      score: "99",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI-ycnCXMU_IhRLsRqnkOnGExWNNDFFy07Kg&usqp=CAU",
      children: [
        {
          name: "David HR",
          score: "99",
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI-ycnCXMU_IhRLsRqnkOnGExWNNDFFy07Kg&usqp=CAU",
          designation: "HR",
          email: "david.hr@example.com",
          manager: "Alice Anderson",
          children: [],
        },
        {
          name: "Eric CFO",
          score: "99",
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI-ycnCXMU_IhRLsRqnkOnGExWNNDFFy07Kg&usqp=CAU",
          designation: "HR",
          email: "eric.cfo@example.com",
          manager: "Alice Anderson",
          children: [],
        },
        {
          name: "Frank Sales Mgr",
          score: "99",
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI-ycnCXMU_IhRLsRqnkOnGExWNNDFFy07Kg&usqp=CAU",
          designation: "HR",
          email: "frank.sales@example.com",
          manager: "Carol CEO",
          children: [
            {
              name: "Jack Sales TL",
              designation: "Sales Team Leader",
              email: "jack.sales@example.com",
              manager: "Frank Sales Mgr",
              children: [
                {
                  name: "Rachel Sales Rep",
                  designation: "Sales Representative",
                  email: "rachel.sales@example.com",
                  manager: "Jack Sales TL",
                  children: [],
                },
                {
                  name: "Sam Sales Rep",
                  designation: "Sales Representative",
                  email: "sam.sales@example.com",
                  manager: "Jack Sales TL",
                  children: [],
                },
              ],
            },
            {
              name: "Kelly Sales TL",
              designation: "Sales Team Leader",
              email: "kelly.sales@example.com",
              manager: "Frank Sales Mgr",
              children: [
                {
                  name: "Tina Sales Rep",
                  designation: "Sales Representative",
                  email: "tina.sales@example.com",
                  manager: "Kelly Sales TL",
                  children: [],
                },
                {
                  name: "Victor Sales Rep",
                  designation: "Sales Representative",
                  email: "victor.sales@example.com",
                  manager: "Kelly Sales TL",
                  children: [],
                },
              ],
            },
          ],
        },
        {
          name: "Grace Marketing Mgr",
          designation: "Marketing Manager",
          email: "grace.marketing@example.com",
          manager: "Carol CEO",
          children: [
            {
              name: "Leo Mktg TL",
              designation: "Marketing Team Leader",
              email: "leo.marketing@example.com",
              manager: "Grace Marketing Mgr",
              children: [
                {
                  name: "Wendy Mktg Rep",
                  designation: "Marketer",
                  email: "wendy.marketing@example.com",
                  manager: "Leo Mktg TL",
                  children: [],
                },
                {
                  name: "Xavier Mktg Rep",
                  designation: "Marketer",
                  email: "xavier.marketing@example.com",
                  manager: "Leo Mktg TL",
                  children: [],
                },
              ],
            },
            {
              name: "Maria Mktg TL",
              designation: "Marketing Team Leader",
              email: "maria.marketing@example.com",
              manager: "Grace Marketing Mgr",
              children: [],
            },
          ],
        },
        {
          name: "Henry Ops Mgr",
          designation: "Operations Manager",
          email: "henry.ops@example.com",
          manager: "Carol CEO",
          children: [
            {
              name: "Nathan Ops TL",
              designation: "Operations Team Leader",
              email: "nathan.ops@example.com",
              manager: "Henry Ops Mgr",
              children: [
                {
                  name: "Yara Ops Staff",
                  designation: "Operations Staff",
                  email: "yara.ops@example.com",
                  manager: "Nathan Ops TL",
                  children: [],
                },
                {
                  name: "Zach Ops Staff",
                  designation: "Operations Staff",
                  email: "zach.ops@example.com",
                  manager: "Nathan Ops TL",
                  children: [],
                },
              ],
            },
            {
              name: "Olivia Ops TL",
              designation: "Operations Team Leader",
              email: "olivia.ops@example.com",
              manager: "Henry Ops Mgr",
              children: [],
            },
          ],
        },
        {
          name: "Irene Tech Mgr",
          designation: "Technology Manager",
          email: "irene.tech@example.com",
          manager: "Carol CEO",
          children: [
            {
              name: "Paul Tech TL",
              designation: "Technology Team Leader",
              email: "paul.tech@example.com",
              manager: "Irene Tech Mgr",
              children: [
                {
                  name: "Chris Tech Staff",
                  designation: "Technology Staff",
                  email: "chris.tech@example.com",
                  manager: "Paul Tech TL",
                  children: [],
                },
                {
                  name: "Dana Tech Staff",
                  designation: "Technology Staff",
                  email: "dana.tech@example.com",
                  manager: "Paul Tech TL",
                  children: [],
                },
              ],
            },
            {
              name: "Quinn Tech TL",
              designation: "Technology Team Leader",
              email: "quinn.tech@example.com",
              manager: "Irene Tech Mgr",
              children: [
                {
                  name: "Alex Tech Staff",
                  designation: "Technology Staff",
                  email: "alex.tech@example.com",
                  manager: "Quinn Tech TL",
                  children: [],
                },
                {
                  name: "Bella Tech Staff",
                  designation: "Technology Staff",
                  email: "bella.tech@example.com",
                  manager: "Quinn Tech TL",
                  children: [],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
